# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_replacement', 'Tire Replacement'), ('engine_repair', 'Engine Repair'), ('brake_service', 'Brake Service'), ('general_service', 'General Service'), ('transmission', 'Transmission'), ('electrical', 'Electrical'), ('body_work', 'Body Work'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.FloatField(default=0, help_text='Maintenance cost')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('mechanic_name', models.CharField(blank=True, default='', max_length=100)),
                ('service_center', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'maintenance_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
