# Generated by Django 6.0.7 on 2026-07-12 06:41

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(help_text='Vehicle name or model', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('trailer', 'Trailer')], max_length=20)),
                ('max_load_capacity', models.FloatField(help_text='Maximum load capacity in kg')),
                ('current_odometer', models.FloatField(default=0, help_text='Current odometer reading in km')),
                ('acquisition_cost', models.FloatField(default=0, help_text='Acquisition cost in currency')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
