# Generated by Django 6.0.7 on 2026-07-12 06:41

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(choices=[('A', 'Category A - Motorcycle'), ('B', 'Category B - Light Vehicle'), ('C', 'Category C - Heavy Vehicle'), ('D', 'Category D - Passenger Vehicle'), ('E', 'Category E - Articulated Vehicle')], max_length=5)),
                ('license_expiry_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('safety_score', models.FloatField(default=100.0, help_text='Safety score from 0 to 100. Higher is better.')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], default='available', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
