"""
Django settings for transitops project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config

# Patch Django's AutoFields to work seamlessly with MongoDB for contrib models (admin, auth, contenttypes)
from django.db.models.fields import AutoField, BigAutoField, SmallAutoField
from django_mongodb_backend.fields.auto import ObjectIdAutoField

def _patch_mongodb_autofield(cls):
    orig_init = cls.__init__
    def new_init(self, *args, **kwargs):
        if "db_column" not in kwargs or kwargs["db_column"] is None:
            kwargs["db_column"] = "_id"
        orig_init(self, *args, **kwargs)
    cls.__init__ = new_init
    cls.get_internal_type = lambda self: "ObjectIdAutoField"
    cls.to_python = ObjectIdAutoField.to_python
    cls.get_prep_value = ObjectIdAutoField.get_prep_value
    cls.db_type = ObjectIdAutoField.db_type
    cls.rel_db_type = ObjectIdAutoField.rel_db_type

_patch_mongodb_autofield(AutoField)
_patch_mongodb_autofield(BigAutoField)
_patch_mongodb_autofield(SmallAutoField)

# Patch Django REST Framework to handle MongoDB ObjectId across all serializers and JSON rendering
try:
    from rest_framework import fields, serializers, relations
    from rest_framework.utils.encoders import JSONEncoder as DRFJSONEncoder
    from bson import ObjectId

    class ObjectIdField(fields.CharField):
        def to_representation(self, value):
            if value is None:
                return None
            return str(value)

        def to_internal_value(self, data):
            if data is None or data == '':
                return None
            try:
                return ObjectId(str(data))
            except Exception:
                return str(data)

    serializers.ModelSerializer.serializer_field_mapping[ObjectIdAutoField] = ObjectIdField
    serializers.ModelSerializer.serializer_field_mapping[AutoField] = ObjectIdField
    serializers.ModelSerializer.serializer_field_mapping[BigAutoField] = ObjectIdField
    serializers.ModelSerializer.serializer_field_mapping[SmallAutoField] = ObjectIdField

    orig_pk_to_rep = relations.PrimaryKeyRelatedField.to_representation
    def _pk_to_rep(self, value):
        try:
            return str(value.pk)
        except AttributeError:
            return str(value)
    relations.PrimaryKeyRelatedField.to_representation = _pk_to_rep

    orig_default = DRFJSONEncoder.default
    def _drf_json_default(self, obj):
        if isinstance(obj, ObjectId):
            return str(obj)
        return orig_default(self, obj)
    DRFJSONEncoder.default = _drf_json_default
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    'django_filters',
    'rest_framework_simplejwt',
    # Local apps
    'accounts',
    'vehicles',
    'drivers',
    'trips',
    'maintenance',
    'expenses',
    'dashboard',
    'analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transitops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transitops.wsgi.application'


# Database — MongoDB Atlas via django-mongodb-backend
# https://www.mongodb.com/docs/languages/python/django-mongodb/current/

MONGODB_URI = config('MONGODB_URL', default='mongodb://localhost:27017/transitops')

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'transitops',
        'HOST': MONGODB_URI,
        'CLIENT': {
            'host': MONGODB_URI,
        },
    }
}


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
}


# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}


# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ORIGIN',
    default='http://localhost:5173,http://localhost:3000',
).split(',')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
