# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('cargo_weight', models.FloatField(help_text='Cargo weight in kg')),
                ('planned_distance', models.FloatField(help_text='Planned distance in km')),
                ('actual_distance', models.FloatField(blank=True, help_text='Actual distance in km', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_odometer', models.FloatField(blank=True, null=True)),
                ('end_odometer', models.FloatField(blank=True, null=True)),
                ('fuel_consumed', models.FloatField(blank=True, help_text='Fuel consumed in liters', null=True)),
                ('revenue', models.FloatField(default=0, help_text='Revenue earned from this trip')),
                ('notes', models.TextField(blank=True, default='')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
